---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink : /:year
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Tanmoy Sanyal's homepage"
keywords:    "tba1, tba2"
description: "Personal website"
favicon:     "lightbulb-o"
touch_icon:  "lightbulb-o"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#0C0E0D'
  white:     '#FFFFFF'
  blue:      '#256697'
  green:     '#13613A'
  purple:    '#48397C'
  orange:    '#CC1414'
  turquoise: '#CBE9FC'
  grey:      '#A9A9A9'
