name: Build and Deploy Tanmoy's Website

on:
  push:
    branches: main
  
  workflow_dispatch:

permissions:
  packages: read
  contents: read
  attestations: write
  id-token: write

jobs:
  build-my-resume:
    name: build my resume
    runs-on: ubuntu-latest

    # container:
    #   image: ghcr.io/tanmoy7989/tanmoy7989.github.io/tsanyal-resume:latest
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: pull docker container
        run: \
          docker loging ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && 
          docker pull ghcr.io/tanmoy7989/tanmoy7989.github.io/tsanyal-resume:latest

      - name: run docker container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/tanmoy7989/tanmoy7989.github.io/tsanyal-resume:latest
          options: -v ${{ github.workspace }}/resume/content:/home/content
          run: \
            npm run export
            ls /home/content
      
      - name: copy resume to assets
        run: cp ${{ github.workspace }}/resume/content/resume.pdf ${{ github.workspace }}/assets/docs/resume/resume.pdf
  