name: Build and Deploy Tanmoy's Website

on:
  push:
    branches: main
  
  workflow_dispatch:

permissions:
  packages: read

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
  resume:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      uses: addnab/docker-run-action@v3
      with:
          image: ghcr.io/tanmoy7989/tanmoy7989.github.io/tsanyal-resume:latest
          options: -v ./resume/content:/home/content
          run: npm run export
      