name: Build and Deploy Tanmoy's Website

on:
  push:
    branches: main
  
  workflow_dispatch:

# permissions:
#   actions: read|write
#   contents: read|write
#   pages: read|write
#   id-token: write

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
  resume:
    runs-on: ubuntu-latest
    needs: checkout
    name: resume
    container:
      image: ghcr.io/tanmoy7989/tanmoy7989.github.io/tsanyal-resume:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - ./resume/content:/home/content
    steps:
        - run: npm run export
    
  copy-resume:
    needs: resume
    name: copy-resume
    runs-on: ubuntu-latest
    steps:
      - run: cp resume/content/resume.pdf assets/docs/resume/resume.pdf
  